/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PrestamoController;
import controlador.PrestamosListaController;
import entidades.Libro;
import modelo.MetodosListaPrestamo;
import modelo.MetodosModeloPrestamo;

/**
 *
 * @author kasak
 */
public class estudianteMenu extends javax.swing.JFrame {

    /**
     * Creates new form estudianteMenu
     */
    public estudianteMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitConsultarLibro = new javax.swing.JMenuItem();
        mitEstanteria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("MENU estudiante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreria-digital.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 250, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servidor-en-la-nube.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servidor-en-la-nube.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 100, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel5.setText("Consultar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        jLabel6.setText("Estantería");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jMenu1.setBackground(new java.awt.Color(255, 51, 0));
        jMenu1.setForeground(new java.awt.Color(0, 0, 51));
        jMenu1.setText("Opciones");

        mitConsultarLibro.setText("ConsultarLibro");
        mitConsultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitConsultarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(mitConsultarLibro);

        mitEstanteria.setBackground(new java.awt.Color(255, 51, 0));
        mitEstanteria.setForeground(new java.awt.Color(0, 0, 51));
        mitEstanteria.setText("Estanteria");
        mitEstanteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEstanteriaActionPerformed(evt);
            }
        });
        jMenu1.add(mitEstanteria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitEstanteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEstanteriaActionPerformed
        ListaLibrosPrestados vista = new ListaLibrosPrestados();
        Libro lib = new Libro();
        MetodosListaPrestamo modelo = new MetodosListaPrestamo();
        PrestamosListaController Controlador = new PrestamosListaController(lib, modelo, vista);
       vista.setTitle("Menu estudiantil");
       vista.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_mitEstanteriaActionPerformed

    private void mitConsultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultarLibroActionPerformed
             ConsultasLibro vista = new ConsultasLibro();
            Libro lib = new Libro();
            MetodosModeloPrestamo MP = new MetodosModeloPrestamo();
        PrestamoController Prestamo = new PrestamoController(lib, MP, vista);
        vista.setTitle("consulta de libros");
        vista.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitConsultarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estudianteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estudianteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estudianteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estudianteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estudianteMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mitConsultarLibro;
    private javax.swing.JMenuItem mitEstanteria;
    // End of variables declaration//GEN-END:variables
}
